/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import clase.*;
import static main.Main.*;

/**
 *
 * @author yo5bdm
 */
public class EditeazaElevi extends javax.swing.JFrame {
    Elev e;
    /**
     * Creates new form AdaugaElevi
     * @param id ID-ul din db al elevului de editat
     */
    public EditeazaElevi(int id) {
        initComponents();
        setLocationRelativeTo(null); //center
        
        e = m.getElev(id);
        if(e!=null) {
            jNume.setText(e.Nume);
            jPrenume.setText(e.Prenume);
            jInitialaTatalui.setText(e.Initiala_tatalui);
            jCNP.setText(e.CNP);
            jVolMatricol.setText(e.Volum_matricol);
            jPaginaMatricol.setText(e.Pagina_matricol);
            jAdresaElev.setText(e.adresa_elev);
            jAdresaParinti.setText(e.adresa_parinti);
            jLoculNasterii.setText(e.locul_nasterii);
            jNationalitate.setText(e.nationalitate);
            jNumeTata.setText(e.nume_tata);
            jNumeMama.setText(e.nume_mama);
            Inmatriculat.setSelected(e.inmatriculat);
            Transferat.setSelected(e.transferat);
            Observatii.setText(e.observatii);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNume = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPrenume = new javax.swing.JTextField();
        jInitialaTatalui = new javax.swing.JTextField();
        jCNP = new javax.swing.JTextField();
        jVolMatricol = new javax.swing.JTextField();
        jPaginaMatricol = new javax.swing.JTextField();
        jAdresaElev = new javax.swing.JTextField();
        jAdresaParinti = new javax.swing.JTextField();
        jLoculNasterii = new javax.swing.JTextField();
        jNationalitate = new javax.swing.JTextField();
        jNumeTata = new javax.swing.JTextField();
        jNumeMama = new javax.swing.JTextField();
        jButtonAdauga = new javax.swing.JButton();
        Inmatriculat = new javax.swing.JCheckBox();
        Transferat = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Observatii = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adaugaa Elevi");

        jLabel1.setText("Nume de familie");

        jLabel2.setText("Prenume");

        jLabel3.setText("Initiala tatalui");

        jLabel4.setText("CNP");

        jLabel5.setText("Volum matricol");

        jLabel6.setText("Pagina matricola");

        jLabel7.setText("Adresa elevului");

        jLabel8.setText("Adresa parintilor");

        jLabel9.setText("Locul nasterii");

        jLabel10.setText("Nationalitatea");

        jLabel11.setText("Numele tatalui");

        jLabel12.setText("Numele mamei");

        jButtonAdauga.setText("Actualizeaza");
        jButtonAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdaugaActionPerformed(evt);
            }
        });

        Inmatriculat.setText("Inmatriculat");

        Transferat.setText("Transferat la alta scoala");

        Observatii.setColumns(20);
        Observatii.setRows(5);
        jScrollPane1.setViewportView(Observatii);

        jLabel13.setText("Observatii:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jNumeTata, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNationalitate, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLoculNasterii, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAdresaParinti, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAdresaElev, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPaginaMatricol, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jVolMatricol, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCNP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInitialaTatalui, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrenume, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                            .addComponent(jNumeMama)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Inmatriculat)
                        .addGap(18, 18, 18)
                        .addComponent(Transferat))
                    .addComponent(jButtonAdauga, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jInitialaTatalui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jVolMatricol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jPaginaMatricol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jAdresaElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jAdresaParinti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLoculNasterii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jNationalitate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jNumeTata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jNumeMama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inmatriculat)
                            .addComponent(Transferat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdauga)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdaugaActionPerformed
        if(!Validare()) {
            Metode.mesajEroare("Va rugam completati toate campurile!");
        } else {
            if(jCNP.getText().trim().length() != 13) {
                Metode.mesajEroare("CNP-ul nu este corect!");
                return;
            }
            Elev e = new Elev(
                    this.e.id, 
                    jNume.getText(),
                    jPrenume.getText(),
                    jInitialaTatalui.getText(),
                    jCNP.getText(),
                    jVolMatricol.getText(),
                    jPaginaMatricol.getText(),
                    jAdresaElev.getText(),
                    jAdresaParinti.getText(),
                    jLoculNasterii.getText(),
                    jNationalitate.getText(),
                    jNumeTata.getText(),
                    jNumeMama.getText(),
                    Inmatriculat.isSelected(), 
                    Transferat.isSelected(), 
                    Observatii.getText()
            );
            m.update(e);
        }
    }//GEN-LAST:event_jButtonAdaugaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Inmatriculat;
    private javax.swing.JTextArea Observatii;
    private javax.swing.JCheckBox Transferat;
    private javax.swing.JTextField jAdresaElev;
    private javax.swing.JTextField jAdresaParinti;
    private javax.swing.JButton jButtonAdauga;
    private javax.swing.JTextField jCNP;
    private javax.swing.JTextField jInitialaTatalui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLoculNasterii;
    private javax.swing.JTextField jNationalitate;
    private javax.swing.JTextField jNume;
    private javax.swing.JTextField jNumeMama;
    private javax.swing.JTextField jNumeTata;
    private javax.swing.JTextField jPaginaMatricol;
    private javax.swing.JTextField jPrenume;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jVolMatricol;
    // End of variables declaration//GEN-END:variables

    private void resetForm() {
        jNume.setText("");
        jPrenume.setText("");
        jInitialaTatalui.setText("");
        jCNP.setText("");
        jVolMatricol.setText("");
        jPaginaMatricol.setText("");
        jAdresaElev.setText("");
        jAdresaParinti.setText("");
        jLoculNasterii.setText("");
        jNationalitate.setText("");
        jNumeTata.setText("");
        jNumeMama.setText("");
        Observatii.setText("");
        Inmatriculat.setSelected(false);
        Transferat.setSelected(false);
    }

    private boolean Validare() {
        return !(jNume.getText().trim().length() == 0 ||
                jPrenume.getText().trim().length() == 0 ||
                jInitialaTatalui.getText().trim().length() == 0 ||
                jCNP.getText().trim().length() == 0 ||
                jVolMatricol.getText().trim().length() == 0 ||
                jPaginaMatricol.getText().trim().length() == 0 ||
                jAdresaElev.getText().trim().length() == 0 ||
                jAdresaParinti.getText().trim().length() == 0 ||
                jLoculNasterii.getText().trim().length() == 0 ||
                jNationalitate.getText().trim().length() == 0 ||
                jNumeTata.getText().trim().length() == 0 ||
                jNumeMama.getText().trim().length() == 0);
    }
}
